version: "3.9"

services:

  db:
    image: mysql:8.0
    container_name: wp_lm_mysql
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wp_lm_mysql
      MYSQL_USER: lm_db1848
      MYSQL_PASSWORD: quelojaquevocetrabalha?
      MYSQL_ROOT_PASSWORD: skathepussycat
    ports:
      - "3306:3306"

  wordpress:
    image: wordpress:php8.2-apache
    container_name: wp_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword